all:
  vars:
    ansible_user: demarzo
    ansible_ssh_private_key_file: ~/.ssh/ansible_ed25519
    ansible_become: true
    ansible_become_method: sudo
    ansible_become_password: "{{ vault_demarzo_password }}"

  children:
    proxmox:
      hosts:
        darrow:
          ansible_host: 10.12.5.11
        sevro:
          ansible_host: 10.12.5.12
        ragnar:
          ansible_host: 10.12.5.13
        sefi:
          ansible_host: 10.12.5.14

    lxc:
      hosts:
        dns1:
          ansible_host: 10.12.5.53
        dns2:
          ansible_host: 10.12.5.54
          ansible_user: root
          ansible_become: false

    vms:
      hosts:
        ops:
          ansible_host: 10.12.30.10

    media:
      hosts:
        victra:
          ansible_host: 10.12.30.50
